### ISSUE TITLE
Redis error when upgrading to 0.14.0-beta

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-dotnet#149]
Reported issue:

> ...by just changing my .csproj to reference `0.14.0-beta` instead of `0-13.0-beta`, and my app stops sending data to Honeycomb.  No other changes.

**Comment by JamieDanielson** [comment]
Potential repro, error when running Console example app on main:

```
Unhandled exception. System.NotSupportedException: StackExchange.Redis IConnectionMultiplexer must be supplied when dependency injection is unavailable. To enable dependency injection use the OpenTelemetry.Extensions.Hosting package.
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.AddRedisInstrumentation(TracerProviderBuilder builder, IConnectionMultiplexer connection, Action`1 configure)
   at Honeycomb.OpenTelemetry.TracerProviderBuilderExtensions.AddHoneycomb(TracerProviderBuilder builder, HoneycombOptions options) in /Users/jamiedanielson/code/honeycomb-opentelemetry-dotnet/src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs:line 87
   at console.Program.Main(String[] args) in /Users/jamiedanielson/code/honeycomb-opentelemetry-dotnet/examples/console/Program.cs:line 21
```

**Comment by JamieDanielson** [comment]
Reviewing our docs and recent changes, I see [PR 129](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/129) added more instrumentation, including Redis which is set to true by default in `HoneycombOptions.cs`:

```cs
        public bool InstrumentStackExchangeRedisClient { get; set; } = true;
```

When I added the line `InstrumentStackExchangeRedisClient = false` to my `HoneycombOptions` (based on [this section of docs](https://docs.honeycomb.io/getting-data-in/dotnet/opentelemetry-distro/#disabling-instrumentation-packages)), I stopped getting an error and data flowed to Honeycomb.
